development:
  clients:
    default:
      database: doorkeeper-mongoid6-development
      hosts:
        - localhost:27017
      options:
        write:
          w: 1

test:
  clients:
    default:
      database: doorkeeper-mongoid6-test
      hosts:
        - localhost:27017
      options:
        write:
          w: 1
